Repository nodeshift/nodeshift, pull requests merged in 2018-04, with the labels that each got.

#210 feat(build.env): add a --build.env flag to specify build config envir…
  README.md
  bin/nodeshift
  index.js
  lib/build-config.js
  lib/definitions/build-strategy.js
  lib/helpers.js
  lib/resource-loader.js
  test/definitions-tests/build-strategy-test.js
  test/helpers-test.js
  test/resource-loader-test.js
Labels: review

#212 add package name sanitisation
  bin/nodeshift
  lib/nodeshift-config.js
  test/nodeshift-config-test.js
Labels: in progress

#217 fix: remove the hardcoded 8080 for ports.
  README.md
  bin/nodeshift
  index.js
  lib/definitions/container.js
  lib/definitions/route-spec.js
  lib/nodeshift-config.js
  lib/resource-enrichers/health-check-enricher.js
  lib/resource-enrichers/service-enricher.js
  test/definitions-tests/container-test.js
  test/definitions-tests/route-spec-test.js
  test/enricher-tests/health-check-enricher-test.js
  test/enricher-tests/service-enricher-test.js
  test/nodeshift-config-test.js
Labels: review

#218 fix: add a name (http) to the service port
  lib/resource-enrichers/service-enricher.js
  test/enricher-tests/service-enricher-test.js
Labels: enhancement, in progress, review
